### PR TITLE
Added projects in README

### PR DESCRIPTION
**Pull request by itsksquare**
Hey, I made those changes mentioned in issue #26 .
I think the table looks better so I've pushed the file with the table, I've attached the screenshots of both files. Also the width of the table cells can't be managed so might look a little messy, I could have fixed that with some screenshots of the projects but wasn't able to take any beginner friendly shots for most of them.
Screenshot 2021-10-05 163427
Screenshot 2021-10-05 163643

### CODE REVIEW

**Review by AM1CODES — COMMENTED** [review]
I feel like the second display looks great but would make the readme a bit long as we add more and more projects. @JackJJCodes what do you think?

**Comment by JackJJCodes** [comment]
I think the table approach has a slight edge over the list approach, as it looks systematic. Also, we would be getting a lot of PR's by the end of October. So the list approach would be exhaustive to read.

**Comment by itsksquare** [comment]
I could rearrange the projects in the table so it doesn't look messy, or add empty spaces to make the cells even
or
Remove the descriptions in the list approach to make it a little shorter

**Comment by AM1CODES** [comment]
> I could rearrange the projects in the table so it doesn't look messy, or add empty spaces to make the cells even or Remove the descriptions in the list approach to make it a little shorter

Alright, lets make the cells even and merge it. I think that will be our best option

**Comment by itsksquare** [comment]
Added those empty spaces to make the table better, but 1 issue could be noticed if someone really focuses, this is what the table looks like in the default view
default
but like this when the Readme file is opened
open

**Comment by JackJJCodes** [comment]
Can you work on fixing the alignment when README file is opened then?

**Comment by JackJJCodes** [comment]
Works for me. @AM1CODES what do you think?

**Review by AM1CODES — APPROVED** [review]
I think we are dragging this too much. I think what we have now looks great and we should continue with that. Great work @itsksquare I am merging this right away.

**Pull request merged**
