### PR TITLE
Scraping data from website

### PR DESCRIPTION
**Pull request by kannangr21**
BeautifulSoup4 is used to scrape data from the dynamic website

### CODE REVIEW

**Comment by kannangr21** [comment]
Kindly add 'hacktoberfest-accepted' label to this PR

**Comment by JackJJCodes** [comment]
@kannangr21 Hey! Could you please put the README file and the .py file in the same folder? You could name it something like Web-Scraper or something.
Thank you!

**Comment by kannangr21** [comment]
@JackJJCodes Changed the folder structure. Check if it's okay.

**Review by AM1CODES — CHANGES_REQUESTED** [review]
We merged a PR just now that makes the Python script folder, so could you just move your files in that folder? or if its a lot of trouble then just delete the previous fork, refork it  and make a new PR so that we dont run into any further issues.

**Comment by kannangr21** [comment]
@AM1CODES I have merged the previous PR you made and my PR.
Now the folder structure is like
Python-Scripts
           |- My folder
           |- The previous PR

**Review by AM1CODES — APPROVED** [review]
The new update looks great. I will give the label as well and merge it.

**Comment by kannangr21** [comment]
Thanks! Kindly add the `hacktoberfest-accepted` label too.

**Pull request merged**
