### PR TITLE
Flower classification web app

### PR DESCRIPTION
**Pull request by inspo13**
Deploy a deep learning Keras model onto a web app using Streamlit.
Upload the image of any flower then the model will predict the correct name of the flower shown in the image.

### CODE REVIEW

**Review by AM1CODES — CHANGES_REQUESTED** [review]
Can you please rename the folder to Flower Classification - Deployed? Because there is already one folder by the name flower classification but it is not deployed. This will help us differentiate better.

**Comment by inspo13** [comment]
Sure.

**Comment by JackJJCodes** [comment]
Apart from renaming the folder, everything looks good to me 👍🏽.

**Review by JackJJCodes — APPROVED** [review]

**Review by AM1CODES — APPROVED** [review]
Yea I think this should work. Merging it.

**Pull request merged**
