### PR TITLE
Hyper Parameter Tuning Keras

### PR DESCRIPTION
**Pull request by AnikaJagati**
CNN model implementation on FashionMNIST dataset
Do verify and merge :)

### CODE REVIEW

**Review by AM1CODES — CHANGES_REQUESTED** [review]
Could you please rename the folder to Fashion MNIST or something more relevant? I think that would make the repo look more organized.

**Comment by AnikaJagati** [comment]
Done!

**Comment by JackJJCodes** [comment]
Cool! I think it looks good now.

**Review by JackJJCodes — APPROVED** [review]

**Comment by AnikaJagati** [comment]
There seems to be some issue with it?
SHould i fork and update again?

**Review by AM1CODES — APPROVED** [review]
Yup looks good to me as well, i will go ahead and merge it.

**Pull request merged**
