### PR TITLE
Face Emotion Recognition using webcam python

### PR DESCRIPTION
**Pull request by pavi-ninjaac**

### CODE REVIEW

**Review by AM1CODES — APPROVED** [review]
Everything looks good to me. Folder structure is also followed properly. Good to merge!

**Comment by AM1CODES** [comment]
Also you can check out this link. It's my implementation of emotion detection. It's a custom architecture which performs much better than VGG. You can just go through it once if you want.
https://www.kaggle.com/aayushmishra1512/emotion-detector

**Review by JackJJCodes — APPROVED** [review]

**Comment by JackJJCodes** [comment]
Looks good to me! Great work @pavi-ninjaac!

**Comment by pavi-ninjaac** [comment]
thank you @JackJJCodes @AM1CODES , i can see it is not merged yet..is there any problem or do i need to change/add anything? if yes, kindly tell me what ...i can make it out

**Comment by AM1CODES** [comment]
@pavi-ninjaac All good. Sorry for the delay in merging. Got caught up in something. Merging it right away.

**Pull request merged**
